export const FETCH_REGISTRATION_USER_DATA_REQUEST =
  "FETCH_REGISTRATION_USER_DATA_REQUEST";
export const FETCH_REGISTRATION_USER_DATA_SUCCESS =
  "FETCH_REGISTRATION_USER_DATA_SUCCESS";
export const FETCH_REGISTRATION_USER_DATA_FAILURE =
  "FETCH_REGISTRATION_USER_DATA_FAILURE";
export const LOG_OUT_CURRENT_USER = "LOG_OUT_CURRENT_USER";
