export const OPEN_PRODUCT_MODAL = "OPEN_PRODUCT_MODAL";
export const CLOSE_PRODUCT_MODAL = "CLOSE_PRODUCT_MODAL";

export const FETCH_PRODUCT_LIST_REQUEST = "FETCH_PRODUCT_LIST_REQUEST";
export const FETCH_PRODUCT_LIST_SUCCESS = "FETCH_PRODUCT_LIST_SUCCESS";
export const FETCH_PRODUCT_LIST_FAILURE = "FETCH_PRODUCT_LIST_FAILURE";
